language: node_js
node_js: 
    - '6'

cache:
  directories:
    - node_modules


install:
  - npm i --global ava

before_script:

script:
  - npm run build

branches:
  only:
    - master
env:
 global:
